apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: bdc
          # Local image.
          imagePullPolicy: Never
          # Container env vars set with image.
#          env:
#            - name: HOST
#              value: "0.0.0.0"
#            - name: PORT
#              value: "3000"
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: frontend
  type: LoadBalancer
